host: 10.119.14.141
port: 1007
#pos_scale: 100
#vel_scale: 10
logger: true
#train_type: "APPROACH"
save_path: "../logs/single_training/"
#max_steps: 2000
random_initial: true
curriculum_easy_resets: 800
curriculum_medium_resets: 800
resume_checkpoint: "simple_attack_275000_steps.zip"
my_initial_speed: 16
aim_assist_enabled: true
aim_assist_gain: 0.55
aim_assist_pitch_sign: 1
aim_assist_yaw_sign: 1
